name: Sync JSON from OneDrive to GitHub

on:
  schedule:
    # chạy mỗi 5 phút
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download JSON from OneDrive
        run: |
          curl -L \
          "https://ttigroup-my.sharepoint.com/personal/hoailuan_nguyen01_ttigroup_com_vn/_layouts/15/download.aspx?SourceUrl=%2Fpersonal%2Fhoailuan%5Fnguyen01%5Fttigroup%5Fcom%5Fvn%2FDocuments%2FLuan%2FDashboard%2FChamCongDashboard%2Fdata%2Ejson" \
          --output data.json

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if [[ `git status --porcelain` ]]; then
            echo "Detected changes → committing..."
            git add data.json
            git commit -m "Auto-sync data.json from OneDrive"
            git push https://x-access-token:${GH_PAT}@github.com/hoailuan0311-code/ChamCongDashboard.git HEAD:main
          else
            echo "No changes detected → nothing to commit."
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
