name: Sync JSON from OneDrive to GitHub

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download JSON from OneDrive
        run: |
          curl -L \
          "https://ttigroup-my.sharepoint.com/:u:/g/personal/hoailuan_nguyen01_ttigroup_com_vn/IQCPvIqJNqnfRJWphSuQFz4QAQ3e4D391kftXWxpD9lwLsM?e=sVxzMk&download=1" \
          --output data.json

      - name: Commit updated JSON
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/hoailuan0311-code/ChamCongDashboard.git

          if [[ `git status --porcelain` ]]; then
            echo "Detected changes â†’ committing..."
            git add data.json
            git commit -m "Auto-sync data.json from OneDrive"
            git push origin HEAD:main
          else
            echo "No changes detected"
          fi
